#if(my_boost_included)
#    return()
#endif(my_boost_included)
#set(my_boost_included true)
#
find_package(boost COMPONENTS filesystem system regex)
if(Boost_FOUND)
    include_directories(${Boost_INCLUDE_DIRS})
    set(Boost_USE_MULTITHREADED     ON)
    set(Boost_USE_STATIC_RUNTIME    OFF)
endif()
